name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest
        # Put your action repo here
        uses: yunwei37/OpenAI-Continuous-Translator@master
        with:
          git_repo_url: https://github.com/yunwei37/GIS-image-vis
          api_key: "xxx"
